# Generated by Django 4.2.1 on 2023-07-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='drop_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
