# Generated by Django 4.2.1 on 2023-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_customuser_is_dropshipper_customuser_is_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(default=False),
        ),
    ]
