# Generated by Django 4.2.1 on 2023-07-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='hidden_from_drop',
            field=models.BooleanField(default=False),
        ),
    ]
