# Generated by Django 4.2.1 on 2023-07-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_subcategory_hidden_from_drop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='sell_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
