# Generated by Django 4.2.1 on 2023-07-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_rename_price_product_sell_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='drop_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='hidden_from_drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder',
            field=models.BooleanField(default=False),
        ),
    ]
