# Generated by Django 4.2.1 on 2023-07-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_storage_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
