# Generated by Django 4.2.1 on 2023-07-25 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_employee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='dashboards.vendor', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
