# Generated by Django 4.2.1 on 2023-07-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='dashboards.storage'),
        ),
    ]
