# Generated by Django 4.2.1 on 2023-07-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_product_category_product_subcategory_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
