# Generated by Django 4.2.1 on 2023-07-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_alter_employee_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='schedule',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
