# Generated by Django 4.2.1 on 2023-07-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_storage_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='storage',
            name='schedule',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
