# Generated by Django 4.2.1 on 2023-07-26 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_alter_storage_address_alter_storage_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='dashboards.vendor', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
