# Generated by Django 4.2.1 on 2023-07-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_storage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='dashboards.storage', verbose_name='Склад')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='dashboards.vendor', verbose_name='Поставщик')),
            ],
        ),
    ]
