# Generated by Django 4.2.1 on 2023-07-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Сектор', 'verbose_name_plural': 'Сектора'},
        ),
        migrations.AlterField(
            model_name='sector',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.vendor', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='dashboards.storage', verbose_name='Сектор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.vendor', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
    ]
