# Generated by Django 4.2.1 on 2023-07-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_alter_sector_options_alter_sector_user_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='dashboards.sector', verbose_name='Сектор'),
        ),
    ]
