# Generated by Django 4.2.1 on 2023-07-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='dropshippers',
            field=models.ManyToManyField(related_name='dropshippers', to='dashboards.dropshipper'),
        ),
    ]
