# Generated by Django 4.2.1 on 2023-07-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_alter_shelf_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
