# Generated by Django 4.2.1 on 2023-08-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_alter_sector_name_alter_shelf_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dashboards.storage', verbose_name='Склад')),
            ],
        ),
    ]
