# Generated by Django 4.2.1 on 2023-08-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0018_storagecontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagecontact',
            options={'verbose_name': 'Контакты склада'},
        ),
        migrations.AlterField(
            model_name='storagecontact',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
