# Generated by Django 4.2.1 on 2023-08-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0019_alter_storagecontact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagecontact',
            options={'verbose_name': 'Контакт склада', 'verbose_name_plural': 'Контакты склада'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='dashboards.storage'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='storagecontact',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='storagecontact',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='storagecontact',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
    ]
