# Generated by Django 4.2.1 on 2023-08-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0021_contacttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttype',
            name='value',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
