# Generated by Django 4.2.1 on 2023-08-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0022_contacttype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='schedule',
            field=models.TextField(blank=True, verbose_name='График работы'),
        ),
    ]
